name: CI - Build and Push Docker Images

on:
  push:
    branches: [ "master", "dev", "prod" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/taskmanager-frontend
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/taskmanager-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker image tags
        id: vars
        run: |
          BRANCH=$(echo "${{ github.ref }}" | awk -F/ '{print $3}')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "frontend_tag=${{ secrets.DOCKER_USERNAME }}/taskmanager-frontend:$BRANCH" >> $GITHUB_OUTPUT
          echo "backend_tag=${{ secrets.DOCKER_USERNAME }}/taskmanager-backend:$BRANCH" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.frontend_tag }} ./client
          docker push ${{ steps.vars.outputs.frontend_tag }}

      - name: Build and Push Backend Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.backend_tag }} ./backend
          docker push ${{ steps.vars.outputs.backend_tag }}

  update-infra-repo:
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout Infra repo
        uses: actions/checkout@v4
        with:
          repository: OletiSatishKumar/TaskManager_MERN_Infra_3
          token: ${{ secrets.GH_TOKEN }}
          path: infra

      - name: Update image tags in values file
        run: |
          cd helm/taskmanager

          if [ "$BRANCH" = "dev" ]; then
            FILE="values-dev.yaml"
          elif [ "$BRANCH" = "prod" ]; then
            FILE="values-prod.yaml"
          else
            FILE="values-dev.yaml"
          fi

          echo "Updating image tags in $FILE"

          sed -i "s|image: .*/taskmanager-frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/taskmanager-frontend:$BRANCH|" $FILE
          sed -i "s|image: .*/taskmanager-backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/taskmanager-backend:$BRANCH|" $FILE

      - name: Commit and push changes
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🤖 Update image tags to $BRANCH"
          git push origin master
