name: CI - Build and Push Docker Images

on:
  push:
    branches: [ "master", "dev", "prod" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    env:
      FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-frontend
      BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker image tag with timestamp
        id: vars
        run: |
          BRANCH="${{ github.ref_name }}"
          TIMESTAMP=$(date +%Y%m%d-%H%M)
          TAG="$BRANCH-$TIMESTAMP"

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "frontend_tag=${{ env.FRONTEND_IMAGE }}:$TAG" >> $GITHUB_OUTPUT
          echo "backend_tag=${{ env.BACKEND_IMAGE }}:$TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Create .env.local from secret
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > ./client/.env.local

      - name: Optional - Duplicate for production
        run: cp ./client/.env.local ./client/.env.production.local

      - name: Build and Push Frontend Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.frontend_tag }} ./client
          docker push ${{ steps.vars.outputs.frontend_tag }}

      - name: Build and Push Backend Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.backend_tag }} ./backend
          docker push ${{ steps.vars.outputs.backend_tag }}

  update-infra-repo:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra repo
        uses: actions/checkout@v4
        with:
          repository: OletiSatishKumar/TaskManager_MERN_Infra_3
          token: ${{ secrets.GH_TOKEN }}
          path: infra

      # Optional: Install yq if you prefer it over sed
      # - name: Install yq
      #   run: |
      #     sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      #     sudo chmod +x /usr/bin/yq

      - name: Update image tags in Helm values file
        run: |
          cd infra/helm/taskmanager
          cat infra/helm/taskmanager/$FILE

          case "${{ github.ref_name }}" in
            dev) FILE="values-dev.yaml" ;;
            prod) FILE="values-prod.yaml" ;;
            *) FILE="values-dev.yaml" ;;
          esac

          echo "Updating image tags in $FILE"
          TAG="${{ needs.build-and-push.outputs.tag }}"

          # ✅ Using spacing-aware sed for matching
          sed -i "s|^\( *image: \).*taskmanager-frontend:.*$|\1${{ env.FRONTEND_IMAGE }}:$TAG|" $FILE
          sed -i "s|^\( *image: \).*taskmanager-backend:.*$|\1${{ env.BACKEND_IMAGE }}:$TAG|" $FILE

          # ✅ Or uncomment below to use yq instead of sed
          # yq eval ".frontend.image = \"${{ env.FRONTEND_IMAGE }}:$TAG\"" -i $FILE
          # yq eval ".backend.image = \"${{ env.BACKEND_IMAGE }}:$TAG\"" -i $FILE

      - name: Commit and push changes
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "🤖 Update image tags to ${{ needs.build-and-push.outputs.tag }}"
            git push origin master
          fi
