name: CI Build and Push to DockerHub

on:
  push:
    branches: [master, dev]

env:
  REGISTRY: docker.io
  IMAGE_NAME_FRONTEND: taskmanager-frontend
  IMAGE_NAME_BACKEND: taskmanager-backend
  INFRA_REPO: OletiSatishKumar/TaskManager_MERN_Infra_2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout App Code
      uses: actions/checkout@v3

    - name: Set Build Tag
      run: echo "BUILD_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_FRONTEND:$BUILD_TAG ./client
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_FRONTEND:$BUILD_TAG

    - name: Build and Push Backend Image
      run: |
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_BACKEND:$BUILD_TAG ./backend
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_BACKEND:$BUILD_TAG

    - name: Clone Infra Repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ env.INFRA_REPO }}.git infra-repo

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Update Dev Patch Deployment with New Image Tags
      run: |
        cd infra-repo/dev
        yq e '(.spec.template.spec.containers[] | select(.name == "backend") .image) = "${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:${{ env.BUILD_TAG }}"' -i patch-deployment.yaml
        yq e '(.spec.template.spec.containers[] | select(.name == "frontend") .image) = "${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-frontend:${{ env.BUILD_TAG }}"' -i patch-deployment.yaml

    - name: Commit and Push Changes to Infra Repo
      run: |
        cd infra-repo
        git add dev/patch-deployment.yaml
        git commit -m "Update image tags to $BUILD_TAG from CI workflow" || echo "No changes to commit"
        git push origin master
